# Generated by Django 2.2 on 2019-04-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='heading title')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Sub heading',
                'verbose_name_plural': 'Sub headings',
                'ordering': ('foreignkey__order', 'foreignkey__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.heading',),
        ),
        migrations.CreateModel(
            name='UpperHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Upper heading',
                'verbose_name_plural': 'Upper headings',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.heading',),
        ),
        migrations.AddField(
            model_name='heading',
            name='foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.UpperHeading', verbose_name='Upper heading'),
        ),
    ]
