# Generated by Django 2.2.2 on 2019-06-08 17:23

import articles.models
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    replaces = [('articles', '0001_initial'), ('articles', '0002_article'), ('articles', '0003_auto_20190409_1732'), ('articles', '0004_auto_20190415_0959'), ('articles', '0005_comment'), ('articles', '0006_comment_author'), ('articles', '0007_auto_20190419_0943'), ('articles', '0008_article_foreignkey_to_boat'), ('articles', '0009_heading_foreignkey_to_boat'), ('articles', '0010_auto_20190423_0950'), ('articles', '0011_auto_20190423_0952'), ('articles', '0012_auto_20190426_1000'), ('articles', '0013_auto_20190507_2237'), ('articles', '0014_article_show'), ('articles', '0015_auto_20190513_1722')]

    initial = True

    dependencies = [
        ('boats', '0016_auto_20190422_1539'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0012_auto_20190416_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='heading title')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Sub heading',
                'verbose_name_plural': 'Sub headings',
                'ordering': ('foreignkey__order', 'foreignkey__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.heading',),
        ),
        migrations.CreateModel(
            name='UpperHeading',
            fields=[
            ],
            options={
                'verbose_name': 'Upper heading',
                'verbose_name_plural': 'Upper headings',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.heading',),
        ),
        migrations.AddField(
            model_name='heading',
            name='foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.UpperHeading', verbose_name='Upper heading'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please add a title', max_length=50, verbose_name='Article header')),
                ('content', models.TextField(blank=True, help_text='Please briefly describe the article', verbose_name='Description of the article')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published at')),
                ('url_to_article', models.URLField(help_text='Please insert URL of the article', max_length=100, unique=True, verbose_name='URL to the article')),
                ('author', models.ForeignKey(on_delete=models.SET(articles.models.superuser), to=settings.AUTH_USER_MODEL)),
                ('foreignkey_to_subheading', models.ForeignKey(help_text='Please choose subheading', on_delete=django.db.models.deletion.PROTECT, to='articles.SubHeading', verbose_name='Subheading')),
                ('foreignkey_to_boat', models.ForeignKey(blank=True, help_text='Please choose the boat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.BoatModel', verbose_name='Parent boat for article')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
                'unique_together': {('foreignkey_to_subheading', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Please type in comment here', verbose_name='Comment text')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='publish?', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publish date')),
                ('foreignkey_to_article', models.ForeignKey(blank=True, help_text='Please choose the article to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Article')),
                ('foreignkey_to_boat', models.ForeignKey(blank=True, help_text='Please choose the boat to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.BoatModel', verbose_name='Boat')),
                ('author', models.CharField(default=1, help_text='Please type in your name ', max_length=30, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='heading',
            name='one_to_one_to_boat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.BoatModel', verbose_name='correspondent boat for the category'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='articles_ar_created_391982_brin'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='articles_co_created_c2d2b6_brin'),
        ),
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, help_text='Marked articles are shown everywhere, unmarked considered as deleted ones', verbose_name='deleted sigh'),
        ),
    ]
