# Generated by Django 2.2 on 2019-04-09 13:42

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Article description')),
                ('content', models.TextField(blank=True, verbose_name='Description of the article')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published at')),
                ('url_to_article', models.URLField(max_length=100, verbose_name='URL to the article')),
                ('author', models.ForeignKey(on_delete=models.SET(articles.models.superuser), to=settings.AUTH_USER_MODEL)),
                ('foreignkey_to_subheading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.SubHeading', verbose_name='Subheading')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
