# Generated by Django 2.2 on 2019-04-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_auto_20190416_1721'),
        ('articles', '0004_auto_20190415_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Please type in comment here', verbose_name='Comment text')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='publish?', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publish date')),
                ('foreignkey_to_article', models.ForeignKey(blank=True, help_text='Please choose the article to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Article')),
                ('foreignkey_to_boat', models.ForeignKey(blank=True, help_text='Please choose the boat to comment on', null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.BoatModel', verbose_name='Boat')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
