# Generated by Django 2.2 on 2019-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, help_text='Please type in your name ', max_length=30, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
