# Generated by Django 2.2 on 2019-04-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
