# Generated by Django 2.2 on 2019-04-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0016_auto_20190422_1539'),
        ('articles', '0007_auto_20190419_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='foreignkey_to_boat',
            field=models.ForeignKey(blank=True, help_text='Please choose the boat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boats.BoatModel', verbose_name='Parent boat for article'),
        ),
    ]
