# Generated by Django 2.2 on 2019-04-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0016_auto_20190422_1539'),
        ('articles', '0008_article_foreignkey_to_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='foreignkey_to_boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boats.BoatModel', verbose_name='correspondent boat for the category'),
        ),
    ]
