# Generated by Django 2.2 on 2019-04-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_heading_foreignkey_to_boat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='foreignkey_to_boat',
            field=models.ForeignKey(blank=True, help_text='Please choose the boat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.BoatModel', verbose_name='Parent boat for article'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='foreignkey_to_boat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boats.BoatModel', verbose_name='correspondent boat for the category'),
        ),
    ]
