# Generated by Django 2.2 on 2019-04-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190423_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='one_to_one_to_boat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boats.BoatModel', verbose_name='correspondent boat for the category'),
        ),
    ]
