# Generated by Django 2.2.1 on 2019-05-07 19:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190426_1000'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='articles_ar_created_391982_brin'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='articles_co_created_c2d2b6_brin'),
        ),
    ]
