# Generated by Django 2.2.1 on 2019-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190507_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
