# Generated by Django 2.2.1 on 2019-05-13 14:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_show'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, help_text='Marked articles are shown everywhere, unmarked considered as deleted ones', verbose_name='deleted sigh'),
        ),
    ]
