# Generated by Django 2.2.1 on 2019-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20190513_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
