# Generated by Django 2.2.1 on 2019-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20190513_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, help_text='Marked articles are shown everywhere, unmarked considered as deleted ones', verbose_name='deleted mark'),
        ),
    ]
