# Generated by Django 2.2.2 on 2019-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190612_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='change_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
