# Generated by Django 2.2.2 on 2019-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190612_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, help_text='Marked articles are shown everywhere, unmarkedconsidered as deleted ones', verbose_name='deleted mark'),
        ),
    ]
