# Generated by Django 2.2.4 on 2019-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('commit_year', models.PositiveIntegerField()),
                ('commits_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'commits_by_year',
            },
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
