# Generated by Django 2.1.7 on 2019-03-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.BoatModel', verbose_name='Boat ForeignKey'),
        ),
    ]
