# Generated by Django 2.1.7 on 2019-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, help_text='Specifies whether user has been activated or not', verbose_name='Is user activated?'),
        ),
    ]
