# Generated by Django 2.1.7 on 2019-03-29 11:48

import boats.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_auto_20190329_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat_photo',
            field=models.ImageField(blank=True, help_text='Please attach any photo of the boat', upload_to=boats.utilities.get_timestamp_path, verbose_name='Boat photo'),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_primary_photo',
            field=models.ImageField(help_text='Please attach a primary photo of the boat', upload_to=boats.utilities.get_timestamp_path, verbose_name='Boat primary photo'),
        ),
    ]
