# Generated by Django 2.2 on 2019-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_boatmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='email',
            field=models.EmailField(help_text='please type in your email', max_length=254, unique=True, verbose_name="user's email"),
        ),
    ]
