# Generated by Django 2.2 on 2019-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_auto_20190410_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='email',
            field=models.EmailField(help_text='please type in your email address', max_length=254, unique=True, verbose_name="user's email"),
        ),
        migrations.AlterUniqueTogether(
            name='extrauser',
            unique_together={('first_name', 'last_name')},
        ),
    ]
