# Generated by Django 2.2 on 2019-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_auto_20190410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_price',
            field=models.IntegerField(help_text='Please input boat price', verbose_name='price of the boat'),
        ),
    ]
