# Generated by Django 2.2 on 2019-04-12 19:23

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_auto_20190412_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmodel',
            name='manufacturing_interval',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, help_text='Please input beginning  and final year of the  model manufacturing ', null=True, verbose_name='Manufacturing              interval'),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_description',
            field=models.TextField(help_text='Please describe the boat', verbose_name='Boat description'),
        ),
    ]
