# Generated by Django 2.2 on 2019-04-13 05:33

import boats.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_auto_20190412_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatmodel',
            name='manufacturing_interval',
        ),
        migrations.AddField(
            model_name='boatmodel',
            name='first_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='first manufacturing year'),
        ),
        migrations.AddField(
            model_name='boatmodel',
            name='last_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='final manufacturing year'),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_description',
            field=models.TextField(blank=True, help_text='Please describe the boat', verbose_name='Boat description'),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_primary_photo',
            field=models.ImageField(blank=True, help_text='Please attach a primary photo of the boat', upload_to=boats.utilities.get_timestamp_path, verbose_name='Boat primary photo'),
        ),
    ]
