# Generated by Django 2.2 on 2019-04-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_auto_20190413_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmodel',
            name='last_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last manufacturing year'),
        ),
    ]
