# Generated by Django 2.2 on 2019-04-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_auto_20190415_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatmodel',
            options={'ordering': ['-boat_publish_date'], 'verbose_name': 'Boats primary data', 'verbose_name_plural': 'Boats primary data'},
        ),
    ]
