# Generated by Django 2.2 on 2019-04-18 17:54

import boats.utilities
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_auto_20190416_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Please attach any photo of the boat', upload_to=boats.utilities.get_timestamp_path, verbose_name='Boat photo'),
        ),
    ]
