# Generated by Django 2.2 on 2019-04-22 07:58

import boats.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0014_auto_20190419_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat_photo',
            field=models.ImageField(blank=True, upload_to=boats.utilities.get_timestamp_path, verbose_name='Boat photo'),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_mast_type',
            field=models.CharField(choices=[(None, 'Please choose rigging type'), ('SL', 'Sloop'), ('KE', 'Ketch'), ('YA', 'Yawl'), ('CK', 'Cat Ketch')], help_text='Please input boat rigging type', max_length=10, verbose_name='Boat rigging type'),
        ),
    ]
