# Generated by Django 2.2 on 2019-04-25 14:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0017_auto_20190425_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_country_of_origin',
            field=django_countries.fields.CountryField(help_text="Please specify boat's country of origin", max_length=2, verbose_name='Boat country of origin'),
        ),
    ]
