# Generated by Django 2.2 on 2019-04-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0019_auto_20190425_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatmodel',
            name='boat_name',
        ),
    ]
