# Generated by Django 2.2 on 2019-04-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0020_remove_boatmodel_boat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmodel',
            name='boat_name',
            field=models.CharField(db_index=True, default=1, help_text='Please input boat model', max_length=20, unique=True, verbose_name='Boat model'),
            preserve_default=False,
        ),
    ]
