# Generated by Django 2.2 on 2019-04-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0021_boatmodel_boat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boats.BoatModel', verbose_name='Boat ForeignKey'),
        ),
    ]
