# Generated by Django 2.2 on 2019-04-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0022_auto_20190429_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatimage',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.BoatModel', verbose_name='Boat ForeignKey'),
        ),
    ]
