# Generated by Django 2.2.2 on 2019-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0027_auto_20190530_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatimage',
            name='change_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_name',
            field=models.CharField(db_index=True, help_text='Please input boat model', max_length=20, unique=True, verbose_name='Boat model'),
        ),
    ]
