# Generated by Django 2.2.2 on 2019-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0028_auto_20190612_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmodel',
            name='change_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
