# Generated by Django 2.2.2 on 2019-06-22 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_boto.s3.storage


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0032_auto_20190621_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maptemplatemodel',
            options={'verbose_name': 'map template', 'verbose_name_plural': 'map templates'},
        ),
        migrations.RemoveField(
            model_name='maptemplatemodel',
            name='boat_id',
        ),
        migrations.AddField(
            model_name='maptemplatemodel',
            name='boat',
            field=models.OneToOneField(default=53, on_delete=django.db.models.deletion.CASCADE, to='boats.BoatModel', verbose_name='parent boat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maptemplatemodel',
            name='map_template',
            field=models.FileField(error_messages={'invalid_extension': 'Only *.html files are allowed'}, storage=django_boto.s3.storage.S3Storage(), unique=True, upload_to='maps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('html',))], verbose_name='map template'),
        ),
    ]
