# Generated by Django 2.2.2 on 2019-06-25 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0033_auto_20190622_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author of the entry'),
            preserve_default=False,
        ),
    ]
