# Generated by Django 2.2.3 on 2019-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0034_auto_20190625_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmodel',
            name='boat_mast_type',
            field=models.CharField(choices=[(None, 'Please choose  the rigging type'), ('SL', 'Sloop'), ('KE', 'Ketch'), ('YA', 'Yawl'), ('CK', 'Cat Ketch'), ('CU', 'Cutter')], help_text='Please input boat rigging type', max_length=10, verbose_name='Boat rigging type'),
        ),
    ]
