# Generated by Django 2.2.4 on 2019-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0035_auto_20190707_1253'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boatmodel',
            constraint=models.CheckConstraint(check=models.Q(first_year__gte=1950), name='first_year__gte=1950'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='boatimage',
            order_with_respect_to='boat',
        ),
    ]
