# Generated by Django 2.2.6 on 2019-10-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191010_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
