# Generated by Django 2.2.6 on 2019-10-13 14:11

import django.contrib.postgres.search
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='textsearchable_index_col',
            field=django.contrib.postgres.search.SearchVectorField(default=django.contrib.postgres.search.SearchVector('english', django.db.models.expressions.F('description'))),
        ),
    ]
