# Generated by Django 2.2.6 on 2019-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_textsearchable_index_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='config',
            field=models.CharField(default='english', max_length=25),
        ),
    ]
