# Generated by Django 2.2.6 on 2019-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='config',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='english', max_length=25),
        ),
    ]
