# Generated by Django 2.2.6 on 2019-10-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191013_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='language',
            new_name='lang',
        ),
    ]
