# Generated by Django 2.2.6 on 2019-10-14 20:18

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trigger_999'),
    ]

    try:
        con = ContentType.objects.get_by_natural_key(app_label='api', model='product')

        operations = [
            migrations.RunSQL(
                """
                CREATE INDEX if not exists 
                decription_fts_gin_idx ON api_product 
                USING GIN (to_tsvector('english', description))
                """,
                reverse_sql=
                """
                DROP INDEX if exists decription_fts_gin_idx
                """
            )
        ]

    except ContentType.DoesNotExist:
        operations = []
