# Generated by Django 2.2.6 on 2019-10-16 20:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191016_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='api_page_content_f84278_gin'),
        ),
    ]
