# Generated by Django 2.2.6 on 2019-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191018_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueWordsTriGramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
    ]
