# Generated by Django 2.2.6 on 2019-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_uniquewordstrigramm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquewordstrigramm',
            name='id',
        ),
        migrations.AlterField(
            model_name='uniquewordstrigramm',
            name='word',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
