# Generated by Django 2.2.6 on 2019-10-18 15:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191018_1335'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='uniquewordstrigramm',
                    index=django.contrib.postgres.indexes.GinIndex(
                        fastupdate=False,
                        fields=['word'],
                        name='words_idx'),
        ),
            ],
            database_operations=[
                migrations.RunSQL(sql=
                                  """
                                  CREATE INDEX words_idx 
                                    ON api_uniquewordstrigramm USING GIN (
                                    word
                                    gin_trgm_ops);
                                  """
                                  ,
                                  reverse_sql=

                                  """
                                  DROP INDEX IF EXISTS words_idx;
                                  """
                                  )
            ]
        )
    ]


# CREATE INDEX words_idx ON words USING GIN (word gin_trgm_ops);
# https://postgrespro.ru/docs/postgresql/11/pgtrgm




